anchors:
  ma200:
    window: 200
    price_field: close
    smoothing: ema
  ma50:
    window: 50
    price_field: close
    smoothing: ema
volatility:
  atr:
    window: 14
    multiplier: 1.5
    price_field: high_low_close
scaling:
  winsorize:
    lower: 0.01
    upper: 0.99
  zscore:
    window: 120
    min_periods: 60
outputs:
  parquet: data/manifests/macro_factor/latest.parquet
  metadata: data/manifests/macro_factor/manifest.json
